admin_users_management:
    path: /usuarios
    controller: App\Controller\Admin\UsersManagementController::list

admin_trainings:
    path: /formaciones
    controller: App\Controller\Admin\TrainingManagementController::list