admin_users_management:
    path: /usuarios
    controller: App\Controller\Admin\UsersManagementController::list

admin_user_enable:
    path: /usuarios/{idUser}/enable
    controller: App\Controller\Admin\UsersManagementController::enable

admin_user_disable:
    path: /usuarios/{idUser}/disable
    controller: App\Controller\Admin\UsersManagementController::disable

admin_user_deny:
    path: /usuarios/{idUser}/deny
    controller: App\Controller\Admin\UsersManagementController::deny

admin_trainings:
    path: /formaciones
    controller: App\Controller\Admin\TrainingManagementController::list

admin_trainings_export:
    path: /formaciones/export
    controller: App\Controller\Admin\TrainingManagementController::export

admin_training_delete:
    path: /formaciones/{idTraining}/delete
    controller: App\Controller\Admin\TrainingManagementController::delete

admin_training_enable:
    path: /formaciones/{idTraining}/enable
    controller: App\Controller\Admin\TrainingManagementController::enable

admin_training_deny:
    path: /formaciones/{idTraining}/deny
    controller: App\Controller\Admin\TrainingManagementController::deny

admin_training_disable:
    path: /formaciones/{idTraining}/disable
    controller: App\Controller\Admin\TrainingManagementController::disable

admin_training_blocks_info:
    path: /formaciones/{idTraining}/blocks-info
    controller: App\Controller\Admin\TrainingManagementController::blocksInfo

admin_competitors_blocks_info:
    path: /formaciones/{idTraining}/competitors-info
    controller: App\Controller\Admin\TrainingManagementController::competitorsInfo

admin_competitors_user_info:
    path: /formaciones/{idUser}/user-info
    controller: App\Controller\Admin\TrainingManagementController::userInfo