users_training_studio:
    path: /formacion/estudio
    controller: App\Controller\Users\TrainingController::studio

users_training_blocks:
    path: /formacion/bloques
    controller: App\Controller\Users\TrainingController::blocks

users_training_date:
    path: /formacion/fecha
    controller: App\Controller\Users\TrainingController::date

users_training_competitors_list:
    path: /formacion/participantes
    controller: App\Controller\Users\CompetitorsController::list

users_training_studio_update:
    path: /formacion/estudio/update
    controller: App\Controller\Users\TrainingController::updateStudio

users_training_blocks_update:
    path: /formacion/bloques/update
    controller: App\Controller\Users\TrainingController::updateBlocks

users_training_date_update:
    path: /formacion/fecha/update
    controller: App\Controller\Users\TrainingController::updateDate

users_training_competitors_add:
    path: /formacion/participantes/add
    controller: App\Controller\Users\CompetitorsController::addCompetitors

users_training_request:
    path: /formacion/solicitar
    controller: App\Controller\Users\TrainingController::requestTraining

users_training_cancel:
    path: /formacion/cancelar
    controller: App\Controller\Users\TrainingController::cancelTraining

users_training_competitors_update:
    path: /formacion/participantes/update
    controller: App\Controller\Users\CompetitorsController::updateCompetitors

users_training_competitors_create:
    path: /formacion/participantes/create
    controller: App\Controller\Users\CompetitorsController::createCompetitors
    methods: [POST]

users_training_competitors_delete:
    path: /formacion/participantes/delete/{idCompetitor}
    controller: App\Controller\Users\CompetitorsController::deleteCompetitors

users_training_list:
    path: /formacion/mis-formaciones
    controller: App\Controller\Users\TrainingController::list