users_training_studio:
    path: /formacion/estudio
    controller: App\Controller\Users\TrainingController::studio

users_training_blocks:
    path: /formacion/bloques
    controller: App\Controller\Users\TrainingController::blocks

users_training_date:
    path: /formacion/fecha
    controller: App\Controller\Users\TrainingController::date

users_training_competitors_list:
    path: /formacion/participantes
    controller: App\Controller\Users\CompetitorsController::list

users_training_studio_update:
    path: /formacion/estudio/update
    controller: App\Controller\Users\TrainingController::updateStudio

users_training_blocks_update:
    path: /formacion/bloques/update
    controller: App\Controller\Users\TrainingController::updateBlocks

users_training_date_update:
    path: /formacion/fecha/update
    controller: App\Controller\Users\TrainingController::updateDate

users_training_competitors_update:
    path: /formacion/participantes/update
    controller: App\Controller\Users\CompetitorsController::updateCompetitors