index:
    path: /
    controller: App\Controller\IndexController:index
login:
    path: /login
    controller: App\Controller\SecurityController::login
signin:
    path: /signin
    controller: App\Controller\IndexController::signin
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

admin:
    resource: routes/admin.yaml
    prefix: /admin

users:
    resource: routes/users.yaml
    prefix: /users
