index:
    path: /
    controller: App\Controller\IndexController:index
login:
    path: /login
    controller: App\Controller\SecurityController::login

admin:
    resource: routes/admin.yaml
    prefix: /admin
